# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSuggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.CharField(max_length=50000)),
                ('user_id', models.CharField(db_index=True, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('apiai_session_id', models.CharField(blank=True, default=b'945b5e4d543146b6a2cb6739e2d6cb53', max_length=500, null=True)),
                ('fav_movies', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
