# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-12 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprefs',
            name='apiai_session_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
