# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesuggest',
            name='id',
        ),
        migrations.AlterField(
            model_name='moviesuggest',
            name='user_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprefs',
            name='apiai_session_id',
            field=models.CharField(blank=True, default=b'4eb3a27d2574468c946f39bedde18ae0', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprefs',
            name='user_id',
            field=models.CharField(max_length=500),
        ),
    ]
