# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-12 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_userprefs_apiai_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprefs',
            name='apiai_session_id',
            field=models.CharField(blank=True, default=b'', max_length=500, null=True),
        ),
    ]
