# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-12 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20161112_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprefs',
            name='apiai_session_id',
            field=models.CharField(blank=True, default=b'72ad58bd73b2471d813d71458a626aae', max_length=500, null=True),
        ),
    ]
